### ISSUE TITLE
Ligne 102 dans Tp2.java: commentaire pas clair

### ISSUE THREAD

**Issue by cybermtl** [cybermtl/G3-Iteration1#1]
* PAS CLAIR  ---->  @param carte3 doit etre entre egal a 51 ou moins <-----

**Comment by casanogab** [comment]
Ce sont les commentaires du tp originale...52 cartes dans le paquet...0 a 51...
-----Original Message-----

**Comment by cybermtl** [comment]
Je vais le changer pour que ce soit plus clair alors.

**Comment by casanogab** [comment]
Parfait !
-----Original Message-----
