### ISSUE TITLE
Nomenclature: Nom de classe

### ISSUE THREAD

**Issue by mastermagic2015** [cybermtl/G3-Iteration1#2]
(0,1 pt) Nomenclature: votre classe devrait se nommer < nom de votre équipe >Sim1.java (ex. JupiterSim1.java)

**Comment by mastermagic2015** [comment]
Il faut que tp2.java soit change pour GofSim1.java

**Comment by casanogab** [comment]
Le code/commentaire appertient a tout le monde si vous voyez quelques chose a ameliorer commit and push !!! :)
-----Original Message-----

**Comment by casanogab** [comment]
done

Date: Tue, 19 May 2015 19:26:40 -0700

**Comment by mastermagic2015** [comment]
Je ne pouvais pas tester donc je n ai rien change toute suite. Seulement creer une l issue.



Best regards, Frederic
 
Date: Wed, 20 May 2015 04:04:22 -0700
